version: "3.9"
services:
  web:
    build:
      context: ./ # Путь к директории с Dockerfile вашего ASP.NET приложения
    container_name: aspnet-api
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=parkmobile;Username=postgres;Password=94monizi

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=94monizi
      - POSTGRES_DB=parkmobile
    ports:
      - "6001:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks:
  app-network: {}